/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ds1.h"

bool_t
xdr_average (XDR *xdrs, average *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->y.y_val, (u_int *) &objp->y.y_len, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_minmax (XDR *xdrs, minmax *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->y.y_val, (u_int *) &objp->y.y_len, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_product (XDR *xdrs, product *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->y.y_val, (u_int *) &objp->y.y_len, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->x.x_val, (u_int *) &objp->x.x_len, 100,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}
